set -e -x

export MODEL_PATH='Qwen/Qwen3-0.6B'
export REWARD_MODEL_PATH='Qwen/Qwen3-0.6B'
export TRAIN_DATA='/root/RL-Factory/data/BFCL/multi-turn/test_example.parquet'
export TEST_DATA='/root/RL-Factory/data/BFCL/multi-turn/test_example.parquet'
export VLLM_USE_V1=1
# export VLLM_ATTENTION_BACKEND=XFORMERS

python3 -m verl.trainer.main_ppo --config-name=rl_factory_ppo_trainer \
    algorithm.adv_estimator=gae\
    data.train_files=$TRAIN_DATA\
    data.val_files=$TEST_DATA\
    data.train_batch_size=1\
    data.max_prompt_length=2560\
    data.max_response_length=512\
    data.return_raw_chat=True\
    data.truncation=left\
    data.filter_overlong_prompts=True\
    actor_rollout_ref.model.path=$MODEL_PATH\
    actor_rollout_ref.actor.optim.lr=3e-7\
    actor_rollout_ref.model.use_remove_padding=True\
    actor_rollout_ref.actor.ppo_mini_batch_size=1\
    actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=1\
    actor_rollout_ref.actor.kl_loss_coef=0.001\
    actor_rollout_ref.actor.kl_loss_type=low_var_kl\
    actor_rollout_ref.model.enable_gradient_checkpointing=True\
    actor_rollout_ref.actor.fsdp_config.param_offload=False\
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=False\
    actor_rollout_ref.actor.state_masking=True\
    actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=1\
    actor_rollout_ref.rollout.tensor_model_parallel_size=1\
    actor_rollout_ref.rollout.name=vllm\
    actor_rollout_ref.rollout.gpu_memory_utilization=0.7\
    actor_rollout_ref.rollout.n=4\
    actor_rollout_ref.rollout.max_turns=4\
    actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=1\
    actor_rollout_ref.ref.fsdp_config.param_offload=False\
    actor_rollout_ref.rollout.enforce_eager=False\
    actor_rollout_ref.rollout.free_cache_engine=False\
    actor_rollout_ref.rollout.mode='async'\
    actor_rollout_ref.env.name=search\
    actor_rollout_ref.env.tool_manager=qwen3\
    actor_rollout_ref.env.enable_thinking=False\
    actor_rollout_ref.env.config_path=envs/configs/bfcl_mcp_tools.pydata\
    actor_rollout_ref.env.use_process_reward=False\
    critic.optim.lr=1e-5\
    critic.model.path=$MODEL_PATH\
    critic.ppo_micro_batch_size_per_gpu=1\
    reward_rollout.if_use_reward_rollout=False\
    reward_rollout.rollout.tensor_model_parallel_size=2\
    reward_rollout.rollout.gpu_memory_utilization=0.7\
    reward_rollout.rollout.model_name=$REWARD_MODEL_PATH\
    reward_rollout.rollout.free_cache_engine=False\
    reward_model.reward_manager=parallel\
    algorithm.kl_ctrl.kl_coef=0.001\
    trainer.critic_warmup=0\
    trainer.logger=['tensorboard']\
    trainer.project_name='ppo_hotpotqa'\
    trainer.experiment_name='step_reward'\
    trainer.n_gpus_per_node=1\
    trainer.nnodes=1\
    trainer.val_before_train=True\
    trainer.default_local_dir=ckpt\
    trainer.default_hdfs_dir=null\
    trainer.save_freq=100\
    trainer.test_freq=10\
    trainer.total_epochs=2 $@ 2>&1 | tee grpo.log
